language: python

python:
  - "2.7"
  - "3.4"

install: 
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "python setup.py develop"

script: 
  - "nosetests"

after_success:
    coveralls

notifications:
    email: false
